# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('condition', models.CharField(max_length=200)),
                ('Usertypes', models.CharField(max_length=50)),
                ('degprog', models.CharField(default='none', max_length=200)),
                ('tb_img', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('types_place', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('types', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.User'),
        ),
    ]
