# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='degprog',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
    ]
