# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20170726_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='degprog',
        ),
    ]
